# ================================================
# RAUF HUSEIN - Hospital Demo Site Generator
# Generates 54 customised hospital websites
# ================================================

$baseDir      = "C:\Project Template A-Z\PROJECT THAT I HAVE TOCH\Rauf Husein\hospital-demos"
$templateFile = "$baseDir\_template\index.html"
$noPhone      = "Call for Number"
$noPhoneRaw   = "+233248837001"
$noPhoneWA    = "233248837001"

$template = [System.IO.File]::ReadAllText($templateFile, [System.Text.Encoding]::UTF8)

$hospitals = @(

  [PSCustomObject]@{ slug="anwiam-hospital";               name="Anwiam Hospital Limited";                   short="Anwiam Hospital";           initial="AH"; phone="026 791 3787"; raw="+233267913787"; wa="233267913787"; address="Afful-Nkwanta, Dr Gabriel Boakye Ave";   tagline="Trusted hospital serving Afful-Nkwanta and surrounding communities with quality care." },
  [PSCustomObject]@{ slug="trinity-health-hospital";       name="Trinity Health Hospital";                   short="Trinity Health";            initial="TH"; phone="026 690 8808"; raw="+233266908808"; wa="233266908808"; address="Kumasi, Ashanti Region";                 tagline="Committed to delivering quality healthcare to every patient in Kumasi." },
  [PSCustomObject]@{ slug="first-care-specialist";         name="First Care Specialist Hospital";            short="First Care Specialist";     initial="FC"; phone="020 245 3699"; raw="+233202453699"; wa="233202453699"; address="4 Mrs. Anane Avenue, Kumasi";            tagline="Specialist healthcare with a personal touch, putting patients first every time." },
  [PSCustomObject]@{ slug="prima-medical-centre";          name="Prima Medical Centre";                      short="Prima Medical";             initial="PM"; phone="050 861 8903"; raw="+233508618903"; wa="233508618903"; address="Paraku Estate, Kumasi";                  tagline="Modern medical care in a comfortable, patient-centred environment at Paraku Estate." },
  [PSCustomObject]@{ slug="trustcare-specialist";          name="Trustcare Specialist Hospital";             short="Trustcare Specialist";      initial="TC"; phone="020 818 1056"; raw="+233208181056"; wa="233208181056"; address="Kumasi, Ashanti Region";                 tagline="Specialist and fertility care delivered with trust, precision, and genuine compassion." },
  [PSCustomObject]@{ slug="yentumi-boaitey-memorial";      name="Yentumi Boaitey Memorial Hospital";         short="Yentumi Boaitey";           initial="YB"; phone="028 954 8905"; raw="+233289548905"; wa="233289548905"; address="Kumasi, Ashanti Region";                 tagline="A dedicated memorial hospital committed to excellence and compassion in healthcare." },
  [PSCustomObject]@{ slug="garden-city-hospital";          name="Garden City Hospital";                      short="Garden City Hospital";      initial="GC"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Quality healthcare at the heart of Kumasi, the Garden City of Ghana." },
  [PSCustomObject]@{ slug="st-augustine-healthcare";       name="St Augustine Healthcare";                   short="St Augustine Healthcare";   initial="SA"; phone="032 204 7259"; raw="+233322047259"; wa="233322047259"; address="No 19 Blk J, West End Hospital Bypass"; tagline="Faith-driven healthcare serving Kumasi with love, skill, and professionalism." },
  [PSCustomObject]@{ slug="legacy-hospital";               name="Legacy Hospital";                           short="Legacy Hospital";           initial="LH"; phone="020 047 2451"; raw="+233200472451"; wa="233200472451"; address="Kumasi, Ashanti Region";                 tagline="Building a legacy of exceptional, compassionate healthcare in the heart of Kumasi." },
  [PSCustomObject]@{ slug="signetcare-medical";            name="Signetcare Medical Services";               short="Signetcare Medical";        initial="SM"; phone="024 600 4657"; raw="+233246004657"; wa="233246004657"; address="Baba Yara Sports Stadium Rd, Kumasi";    tagline="Professional medical services with a strong commitment to quality and patient care." },
  [PSCustomObject]@{ slug="meduma-clinic-maternity";       name="Meduma Clinic and Maternity Home";          short="Meduma Clinic";             initial="MC"; phone="020 460 3600"; raw="+233204603600"; wa="233204603600"; address="Plot 32, Block A, Meduma, Kumasi";         tagline="Trusted maternity and general healthcare serving the Meduma community with care." },
  [PSCustomObject]@{ slug="mac-hills-specialist";          name="Mac-Hills Specialist Hospital";             short="Mac-Hills Specialist";      initial="MH"; phone="024 404 4013"; raw="+233244044013"; wa="233244044013"; address="27 Lesley OpokuWare Drive, Nhyiaeso";     tagline="Specialist hospital delivering world-class medical care in Kumasi." },
  [PSCustomObject]@{ slug="brebre-clinic";                 name="Brebre Clinic";                             short="Brebre Clinic";             initial="BC"; phone="020 998 6838"; raw="+233209986838"; wa="233209986838"; address="Behind Ahinsan Market, Kumasi";           tagline="Accessible, quality healthcare serving the Ahinsan community every day." },
  [PSCustomObject]@{ slug="siaw-larbi-hospital";           name="Siaw-Larbi Hospital";                       short="Siaw-Larbi Hospital";       initial="SL"; phone="032 202 9420"; raw="+233322029420"; wa="233322029420"; address="Kumasi, Ashanti Region";                 tagline="Reliable, professional hospital care for every patient, every time." },
  [PSCustomObject]@{ slug="mater-dei-hospital";            name="Mater Dei Hospital";                        short="Mater Dei Hospital";        initial="MD"; phone="024 408 8818"; raw="+233244088818"; wa="233244088818"; address="Kumasi, Ashanti Region";                 tagline="Compassionate care rooted in faith, excellence, and respect for every patient." },
  [PSCustomObject]@{ slug="south-patasi-hospital";         name="South Patasi Hospital";                     short="South Patasi Hospital";     initial="SP"; phone="024 248 1119"; raw="+233242481119"; wa="233242481119"; address="15 Dr Danso Dapaah Street, Santasi";       tagline="Trusted community hospital serving South Patasi and Santasi with professional care." },
  [PSCustomObject]@{ slug="mount-zion-hospital";           name="Mount Zion Hospital";                       short="Mount Zion Hospital";       initial="MZ"; phone="032 239 5063"; raw="+233322395063"; wa="233322395063"; address="Atasemanso, 17 6th Crescent, Kumasi";     tagline="Elevated healthcare serving Atasemanso with dedication, skill, and compassion." },
  [PSCustomObject]@{ slug="hart-adventist-hospital";       name="Hart Adventist Hospital";                   short="Hart Adventist Hospital";   initial="HA"; phone="032 249 6567"; raw="+233322496567"; wa="233322496567"; address="Ahinsan Post Office, Lake Road, Kumasi"; tagline="Adventist hospital committed to holistic, compassionate patient care." },
  [PSCustomObject]@{ slug="pima-hospital";                 name="PIMA Hospital Limited";                     short="PIMA Hospital";             initial="PH"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Airport Estate, Kumasi";                 tagline="Professional integrated medical care serving Airport Estate and Kumasi." },
  [PSCustomObject]@{ slug="tophill-hospital";              name="Tophill Hospital";                          short="Tophill Hospital";          initial="TH"; phone="032 239 8235"; raw="+233322398235"; wa="233322398235"; address="Kronum Cementmu, Kumasi";                 tagline="Quality healthcare at the top, serving Kronum with professional excellence." },
  [PSCustomObject]@{ slug="west-end-hospital-kwadaso";     name="West End Hospital";                         short="West End Hospital";         initial="WE"; phone="024 546 0006"; raw="+233245460006"; wa="233245460006"; address="Dr Kwakye-Maafo Avenue, Kwadaso, Kumasi"; tagline="Serving Kwadaso and West Kumasi with comprehensive, accessible medical care." },
  [PSCustomObject]@{ slug="patricia-clark-specialist";     name="Patricia Clark Specialist Hospital";        short="Patricia Clark Hospital";   initial="PC"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Specialist care delivering exceptional medical outcomes for every patient." },
  [PSCustomObject]@{ slug="quality-healthcare-hospital";   name="Quality Health Care Hospital";              short="Quality Healthcare";        initial="QH"; phone="027 770 1452"; raw="+233277701452"; wa="233277701452"; address="Wesleyan Road, Kumasi";                  tagline="Quality medical care delivered with precision and patient-first values." },
  [PSCustomObject]@{ slug="topcare-hospital";              name="Topcare Hospital";                          short="Topcare Hospital";          initial="TC"; phone="054 199 0295"; raw="+233541990295"; wa="233541990295"; address="Kumasi, Ashanti Region";                 tagline="Top-quality care and total commitment to every patient's well-being in Kumasi." },
  [PSCustomObject]@{ slug="summerfield-medical-centre";    name="Summerfield Medical Centre";                short="Summerfield Medical";       initial="SM"; phone="055 256 9585"; raw="+233552569585"; wa="233552569585"; address="Kumasi, Ashanti Region";                 tagline="Modern medical centre offering warmth, expertise, and outstanding patient care." },
  [PSCustomObject]@{ slug="church-of-christ-hospital";     name="Church of Christ Mission Hospital";         short="CoC Mission Hospital";      initial="CC"; phone="027 755 2044"; raw="+233277552044"; wa="233277552044"; address="Bomso Road, Kumasi";                     tagline="Faith-based mission hospital serving Bomso with love, healing, and professional care." },
  [PSCustomObject]@{ slug="all-ages-specialist";           name="All Ages Specialist Hospital";              short="All Ages Specialist";       initial="AA"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Specialist care for patients of all ages, from newborns to seniors." },
  [PSCustomObject]@{ slug="atasomanso-hospital";           name="Atasomanso Hospital";                       short="Atasomanso Hospital";       initial="AT"; phone="024 441 7403"; raw="+233244417403"; wa="233244417403"; address="Atasomanso, Kumasi";                     tagline="Community hospital delivering reliable, compassionate care to Atasomanso." },
  [PSCustomObject]@{ slug="dr-osei-hospital";              name="Dr Osei Hospital";                          short="Dr Osei Hospital";          initial="DO"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Expert physician-led hospital delivering trusted care in the heart of Kumasi." },
  [PSCustomObject]@{ slug="christ-the-king-hospital";      name="Christ the King Hospital";                  short="Christ the King Hospital";  initial="CK"; phone="020 998 6838"; raw="+233209986838"; wa="233209986838"; address="Ahinsan Post Office, Kumasi";            tagline="Christian hospital committed to healing body, mind, and spirit with compassion." },
  [PSCustomObject]@{ slug="keffam-hospital";               name="Keffam Hospital";                           short="Keffam Hospital";           initial="KH"; phone="020 811 1297"; raw="+233208111297"; wa="233208111297"; address="Kumasi, Ashanti Region";                 tagline="Trusted hospital care with outstanding patient satisfaction across Kumasi." },
  [PSCustomObject]@{ slug="omar-hospital";                 name="Omar Hospital";                             short="Omar Hospital";             initial="OH"; phone="026 171 1808"; raw="+233261711808"; wa="233261711808"; address="Old Tafo Nyiaeso, Kumasi";               tagline="Serving Old Tafo and Nyiaeso with reliable, accessible, and affordable healthcare." },
  [PSCustomObject]@{ slug="ahodwo-new-cross-hospital";     name="Ahodwo New Cross Hospital";                 short="Ahodwo New Cross";          initial="AN"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="71 Obei Nkwantabisa Avenue, Ahodwo";    tagline="Trusted hospital serving the Ahodwo community with professional medical care." },
  [PSCustomObject]@{ slug="graceland-specialist";          name="Graceland Specialist Hospital";             short="Graceland Specialist";      initial="GS"; phone="026 400 4383"; raw="+233264004383"; wa="233264004383"; address="Kumasi, Ashanti Region";                 tagline="Grace-filled specialist hospital delivering outstanding medical care in Kumasi." },
  [PSCustomObject]@{ slug="milennium-hospital";            name="Milennium Hospital";                        short="Milennium Hospital";        initial="MH"; phone="024 096 9221"; raw="+233240969221"; wa="233240969221"; address="Kromuase New Site, Kumasi";              tagline="Modern hospital delivering a new era of quality healthcare in Kumasi." },
  [PSCustomObject]@{ slug="siloam-hospital";               name="Siloam Hospital";                           short="Siloam Hospital";           initial="SH"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Sunyani Road, Kumasi";                  tagline="Biblical-inspired healing and compassionate care for every patient in Kumasi." },
  [PSCustomObject]@{ slug="madonna-health-services";       name="Madonna Health Services";                   short="Madonna Health";            initial="MH"; phone="032 205 4819"; raw="+233322054819"; wa="233322054819"; address="Kumasi, Metropolitan";                  tagline="Dedicated health services with a commitment to your total well-being in Kumasi." },
  [PSCustomObject]@{ slug="divine-netcare-hospital";       name="Divine Netcare Hospital";                   short="Divine Netcare";            initial="DN"; phone="054 150 4824"; raw="+233541504824"; wa="233541504824"; address="Kumasi, Ashanti Region";                 tagline="Divinely inspired healthcare serving patients with excellence and compassion." },
  [PSCustomObject]@{ slug="sda-hospital-kumasi";           name="S.D.A. Hospital";                           short="S.D.A. Hospital";           initial="SD"; phone="032 203 2618"; raw="+233322032618"; wa="233322032618"; address="Kumasi, Ashanti Region";                 tagline="Seventh-day Adventist healthcare dedicated to holistic wellness and healing." },
  [PSCustomObject]@{ slug="providence-health-care";        name="Providence Health Care";                    short="Providence Healthcare";     initial="PH"; phone="024 931 2172"; raw="+233249312172"; wa="233249312172"; address="Kumasi, Ashanti Region";                 tagline="Providential care and your trusted health partner in Kumasi, Ghana." },
  [PSCustomObject]@{ slug="powerhouse-hospital";           name="Powerhouse Hospital";                       short="Powerhouse Hospital";       initial="PH"; phone="032 202 7157"; raw="+233322027157"; wa="233322027157"; address="Mile 3, Kumasi";                        tagline="Powerful healthcare delivering strength, healing, and hope to Kumasi." },
  [PSCustomObject]@{ slug="medfam-clinic-maternity";       name="Medfam Clinic and Maternity Home";          short="Medfam Clinic";             initial="MF"; phone="032 208 1560"; raw="+233322081560"; wa="233322081560"; address="Bremen Nkwantuma, Kumasi";               tagline="Family-focused clinic and maternity home serving the Nkwantuma community." },
  [PSCustomObject]@{ slug="royal-ash-hospital";            name="Royal Ash Hospital";                        short="Royal Ash Hospital";        initial="RA"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Royal-standard healthcare delivering excellence for every patient in Kumasi." },
  [PSCustomObject]@{ slug="sda-hospital-bremang";          name="SDA Hospital Bremang";                      short="SDA Hospital Bremang";      initial="SB"; phone=$noPhone;       raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Bremang, Kumasi";                        tagline="Adventist hospital serving the Bremang community with dedication and skill." },
  [PSCustomObject]@{ slug="wood-village-clinic";           name="Wood Village Clinic and Maternity Home";    short="Wood Village Clinic";       initial="WV"; phone="023 239 6350"; raw="+233232396350"; wa="233232396350"; address="Kumasi, Ashanti Region";                 tagline="Warm community clinic and maternity home caring for every family in Kumasi." },
  [PSCustomObject]@{ slug="divine-mercy-hospital";         name="Divine Mercy Hospital";                     short="Divine Mercy Hospital";     initial="DM"; phone="024 499 3919"; raw="+233244993919"; wa="233244993919"; address="Esereso, Kumasi";                       tagline="Mercy-driven hospital care dedicated to the Esereso community." },
  [PSCustomObject]@{ slug="afari-community-hospital";      name="Afari Community Hospital";                  short="Afari Community Hospital";  initial="AC"; phone="024 017 6502"; raw="+233240176502"; wa="233240176502"; address="Nkawie Road, Afari, Kumasi";             tagline="Serving the Afari community with accessible, affordable, compassionate healthcare." },
  [PSCustomObject]@{ slug="rev-walker-mission-hospital";   name="Rev. Walker Mission Hospital";              short="Rev. Walker Mission";       initial="RW"; phone="032 206 1821"; raw="+233322061821"; wa="233322061821"; address="Kumasi, Ashanti Region";                 tagline="Mission hospital delivering inspired healthcare with faith, skill, and compassion." },
  [PSCustomObject]@{ slug="asuyeboa-hospital";             name="Asuyeboa Hospital";                         short="Asuyeboa Hospital";         initial="AY"; phone="032 205 0035"; raw="+233322050035"; wa="233322050035"; address="Asuyeboa, Kumasi";                       tagline="Dedicated hospital care serving the Asuyeboa community with professionalism." },
  [PSCustomObject]@{ slug="global-evangelical-mission";    name="Global Evangelical Mission Hospital";       short="Global Evangelical Mission";initial="GE"; phone=$noPhone;      raw=$noPhoneRaw;    wa=$noPhoneWA;     address="Kumasi, Ashanti Region";                 tagline="Mission-led hospital delivering evangelical healing and care across Kumasi." },
  [PSCustomObject]@{ slug="family-care-hospital-mowire";   name="Family Care Hospital";                      short="Family Care Hospital";      initial="FC"; phone="024 416 1566"; raw="+233244161566"; wa="233244161566"; address="Mowire, Kumasi";                        tagline="Family-centred care for every generation, serving the Mowire community." },
  [PSCustomObject]@{ slug="graceside-hospital";            name="Graceside Hospital";                        short="Graceside Hospital";        initial="GH"; phone="032 209 4400"; raw="+233322094400"; wa="233322094400"; address="Kumasi, Ashanti Region";                 tagline="Grace-led healthcare delivering excellence and compassion to every patient." },
  [PSCustomObject]@{ slug="peace-speciality-hospital";     name="Peace Speciality Hospital Ltd";             short="Peace Speciality Hospital"; initial="PS"; phone="032 207 3698"; raw="+233322073698"; wa="233322073698"; address="Behind Education Office, Kumasi";        tagline="Peaceful specialist healthcare with outstanding patient satisfaction in Kumasi." },
  [PSCustomObject]@{ slug="avicenna-medical-services";     name="Avicenna Medical Services";                 short="Avicenna Medical";          initial="AM"; phone="024 404 2687"; raw="+233244042687"; wa="233244042687"; address="Kumasi-Ejisu Road, Kumasi";              tagline="Evidence-based medicine and compassionate care along the Kumasi-Ejisu corridor." }

)

$count = 0
foreach ($h in $hospitals) {
    $dir = "$baseDir\$($h.slug)"
    New-Item -ItemType Directory -Force -Path $dir | Out-Null

    $html = $template
    $html = $html.Replace('__NAME__',      $h.name)
    $html = $html.Replace('__SHORTNAME__', $h.short)
    $html = $html.Replace('__INITIAL__',   $h.initial)
    $html = $html.Replace('__PHONE__',     $h.phone)
    $html = $html.Replace('__PHONERAW__',  $h.raw)
    $html = $html.Replace('__WHATSAPP__',  $h.wa)
    $html = $html.Replace('__ADDRESS__',   $h.address)
    $html = $html.Replace('__TAGLINE__',   $h.tagline)

    [System.IO.File]::WriteAllText("$dir\index.html", $html, [System.Text.Encoding]::UTF8)
    $count++
    Write-Host "[$count/54] $($h.slug)"
}

Write-Host ""
Write-Host "=========================================="
Write-Host " SUCCESS: $count hospital sites generated"
Write-Host "=========================================="
